trigger:
  branches:
    include:
      - prod  # or your desired branch

pool:
  vmImage: 'windows-latest'  # Use a Windows image for PowerShell

steps:
- checkout: self
  persistCredentials: true  # Allow Git push by reusing the pipeline's credentials

- powershell: |
    # Fetch all branches so that 'main' is available for checkout
    git fetch origin

    # Check out the correct branch (main) to avoid detached HEAD issues
    git checkout main

    # Include the checksum functions
    . .\checksum\checksum.ps1

    # Call the Build-CheckSum function to generate the checksum
    Build-CheckSum -checksumPath ".\checksum\checksum.txt"

    # Git add, commit, and push the checksum file back to the repo
    git config user.email "buildagent@tricare.com.au"
    git config user.name "Build Agent"
    
    git add .\checksum\checksum.txt
    git commit -m "Updated checksum file as part of pipeline"
    git push origin main  # Push back to the 'main' branch

  displayName: 'Generate and Push Checksum'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '.\checksum\checksum.txt'
    artifactName: 'Checksum'
    publishLocation: 'Container'